import { LLMCompleteOptions, LLMCompleteResult } from '../core/types';
import { BaseLLMProvider } from './base-provider';
/**
 * Local mock for development — no API calls. Returns minimal valid JSON.
 */
export class MockLLMProvider extends BaseLLMProvider {
  readonly name = 'mock';

  async checkAvailability(): Promise<boolean> {
    return true;
  }

  async complete(prompt: string, options?: LLMCompleteOptions): Promise<LLMCompleteResult> {
    const codeMatch = prompt.match(/```(?:javascript|typescript|jsx|tsx)?\s*([\s\S]*?)```/);
    const sourceCode = codeMatch?.[1]?.trim() || '';

    const hasJsx = sourceCode.includes('<') && sourceCode.includes('>');
    const targetExtension = hasJsx ? '.tsx' : '.ts';

    const response = JSON.stringify({
      targetCode: sourceCode || '// mock migration output',
      targetExtension,
      exports: [{ name: 'default', kind: 'default', signature: 'default export' }],
      confidence: 0.5,
      warnings: ['Generated by USE_MOCK_AI — not a real LLM conversion'],
    });

    return {
      text: response,
      promptTokens: this.estimateTokens(prompt),
      completionTokens: this.estimateTokens(response),
    };
  }
}
